name: gosleep_remote_project
description: gosleep Remote Project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_blue:
    git: https://github.com/espresso3389/flutter_blue
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Light.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Thin.ttf
    - family: Roboto_Regular
      fonts:
        - asset: assets/fonts/roboto_bold.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
